### ISSUE TITLE
holeio.cfg not generated

### ISSUE THREAD

**Issue by cron410** [anonfunc/holeio#24]
When I follow the install instructions as a regular user, holeio.cfg is not generated. When I visit the local server address it does a basic auth which I have no creds for so I started poking around the code and and started building a config file in the format that I believe python wants to read. It is nowhere near complete and I cannot acccess the config page in the webui because I can't figure out the values for root and host, the values below cause everything to 404. Please provide an example config file, or point me in the right direction on what the values should be. I really want to use your app as it would solve a lot of problems for me.

[web]
user = admin
password = admin
host = 127.0.0.1
root = /home/cron410/projects/holeio/holeio

[directories]
download = /mnt/videos/unsorted/filebot
incomplete = /mnt/videos/unsorted/put.io/temp
blackhole = /mnt/videos/unsorted/put.io/auto

[oauth]
token =
client_id =
client_secret =

[intervals]
polling = 
inactive =

**Comment by anonfunc** [comment]
Host is currently unused, but ideally host and port are configured in the UI rather than an external start script.
Root is the prefix to serve under.  
Example urls with root = / (default): localhost/history
Example urls with root = /holeio: localhost/holeio/history

It does look like there's a bug on first start when it tries to check if you've set a password, but the intent was for all this to be set in the UI, which has some conveniences for getting the oauth stuff.

**Comment by cron410** [comment]
config page (views) comes back with a 404 if host and root are left blank in the config file, or if root is set to /. I added a little hack to views.py to see what hole.io thinks WEBROOT is defined as.

    f = open( 'webroot.txt', 'w' )
    f.write( WEBROOT )
    f.close()
 
After starting the server, file webroot.txt now contains //

If I use the hack from #25 then the value of webroot is / and everything works.

I'm not a dev and barely know python so I don't know where to start fixing that, just dirty hacks to get it working. This was all done on Ubuntu 16.04 LTS.

**Comment by anonfunc** [comment]
Fixed in 2fbd47cc405b8a82fbaa3f00b2668b2666ef439b
